- name: bug
  color: "d73a4a"
- name: enhancement
  color: "a2eeef"
- name: perf
  color: "cfd3d7"
- name: good first issue
  color: "7057ff"
- name: docs
  color: "0075ca"
- name: refactor
  color: "c2e0c6"
- name: wontfix
  color: "ffffff"
- name: duplicate
  color: "cfd3d7"
- name: invalid
  color: "e4e669"
