fallback_category = "Other"

[classification.Pictures]
extensions = [".jpg", ".jpeg", ".png", ".gif"]

[classification.Videos]
extensions = [".mp4", ".mov", ".avi"]

[plugins.exif_renamer]
enabled = true
# Available tokens: {year}, {month}, {day}, {hour}, {minute}, {second}, {model}, {make}
pattern = "{year}-{month}-{day}_{hour}.{minute}.{second}_{model}"

[plugins.id3_renamer]
enabled = true
# Available tokens: {artist}, {album}, {title}, {track_number}, {genre}
pattern = "{artist} - {album} - {track_number:02d} - {title}"
