fallback_category = "Other"


[classification.Pictures]
extensions = [
    ".jpg",
    ".jpeg",
    ".png",
    ".gif",
    ".bmp",
    ".tiff",
    ".svg",
    ".webp",
]

[classification.Videos]
extensions = [".mp4", ".mov", ".avi", ".mkv", ".wmv", ".flv"]

[classification.Documents]
extensions = [".pdf", ".doc", ".docx", ".txt", ".rtf", ".odt"]

[classification.Spreadsheets]
extensions = [".xls", ".xlsx", ".ods", ".csv"]

[classification.Presentations]
extensions = [".ppt", ".pptx", ".odp"]

[classification.Audio]
extensions = [".mp3", ".wav", ".flac", ".aac", ".ogg", ".m4a", ".wma"]

[classification.Archives]
extensions = [".zip", ".tar", ".gz", ".rar", ".7z", ".bz2", ".xz"]

[classification.Scripts]
extensions = [".py", ".js", ".sh", ".bat", ".ps1", ".pl", ".rb"]

[classification.Fonts]
extensions = [".ttf", ".otf", ".woff", ".woff2"]

[classification.Books]
extensions = [".epub", ".mobi"]

[classification.Packages]
extensions = [".deb", ".rpm", ".pkg"]

[plugins.exif]
enabled = true
# Available tokens: {year}, {month}, {day}, {hour}, {minute}, {second}, {model}, {make}
pattern = "{year}-{month}-{day}_{hour}.{minute}.{second}_{model}"

[plugins.id3]
enabled = true
# Available tokens: {artist}, {album}, {title}, {track_number}, {genre}
pattern = "{artist} - {album} - {track_number:02d} - {title}"
