site_name: File-Sorter
repo_url: https://github.com/<ORG>/file-sorter
copyright: © {{ date | year }} Your Name
theme:
  name: material
  logo: assets/logo.png
  palette:
    - scheme: slate
      primary: indigo
nav:
  - Home: index.md
  - User Guide: user_guide.md
  - Architecture: architecture.md
  - Changelog: ../CHANGELOG.md
markdown_extensions: [tables, admonition, codehilite]
