name: Feature Request
description: Suggest an idea or improvement
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Proposal
      description: What should be added or changed?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Optional context, links or images
    validations:
      required: false
