name: CI
on: [push, pull_request]

jobs:
  lint:
    name: "Lint / flake8"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install poetry
      - run: poetry install --with dev
      - run: poetry run flake8

  type-check:
    name: "Type Check / mypy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install poetry
      - run: poetry install --with dev
      - run: poetry run mypy sorter tests

  test:
    name: "Test / pytest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install poetry
      - run: poetry install --with dev
      - run: poetry run pytest
