name: Release
on:
  push:
    tags: ["v*.*.*"]
jobs:
  build:
    strategy:
      matrix: {os: [ubuntu-latest, macos-latest, windows-latest]}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.12"}
      - name: Install build deps
        run: >
          pip install cibuildwheel==2.19 build twine pyinstaller
      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse
      - name: Build sdist
        run: python -m build --sdist -o dist
      - name: Build single-file binary
        run: bash scripts/build_binary.sh
      - uses: actions/upload-artifact@v4
        with: {name: dist, path: wheelhouse/*, if-no-files-found: error}
      - uses: actions/upload-artifact@v4
        with: {name: binary, path: dist/file-sorter*, if-no-files-found: error}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/*
            binary/*

